[package]
name = "game"
version = "0.1.0"
authors = ["Eirik Tobiassen <eiriktob@stud.ntnu.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
image = "0.23.12"
winit = "0.24.0"
rand = "0.8.3"